In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold

df = pd.read_csv('insurance.csv')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [35]:
df['sex'] = pd.get_dummies(df['sex'], drop_first=True, dtype=int)
df['smoker'] = pd.get_dummies(df['smoker'], drop_first=True, dtype=int)
df = pd.get_dummies(df, columns=['region'], drop_first=True, dtype=int)

In [36]:
df

,age,sex,bmi,children,smoker,charges,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,16884.92400,0,0,1
1,18,1,33.770,1,0,1725.55230,0,1,0
2,28,1,33.000,3,0,4449.46200,0,1,0
3,33,1,22.705,0,0,21984.47061,1,0,0
4,32,1,28.880,0,0,3866.85520,1,0,0
...,...,...,...,...,...,...,...,...,...
1333,50,1,30.970,3,0,10600.54830,1,0,0
1334,18,0,31.920,0,0,2205.98080,0,0,0
1335,18,0,36.850,0,0,1629.83350,0,1,0
1336,21,0,25.800,0,0,2007.94500,0,0,1
1337,61,0,29.070,0,1,29141.36030,1,0,0

In [37]:
X = df.drop(columns=['charges'])
y = df['charges']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

We have 8 features after encoding. We encode before doing feature selection because the model understands numbers, not strings. If they were not encoded they would be excluded anyway.

In [38]:
vt = VarianceThreshold(threshold=.1)
vt.fit(X_train)
kept = X_train.columns[vt.get_support()].tolist()
kept

['age',
 'sex',
 'bmi',
 'children',
 'smoker',
 'region_northwest',
 'region_southeast',
 'region_southwest']

A low variance feature is not useful for prediction because no matter how the target changes, the feature won't change much. This won't give the model any idea of how it contributes to target variable change.